- src/locales/fi.json
- src/router/index.ts
- src/views/arviointipyynto.vue
- src/views/koejakso-tavoitteet.vue
- src/views/koejakso.vue
- yarn.lock
- koejakson tavoitteet sivu + linkit sivulle
- pieniä refaktorointeja
> Uoelsa 259 koejakson tavoitteet

- src/components/arviointipyynto-card/arviointipyynto-card.vue
- src/forms/arviointipyynto-form.vue
- src/locales/fi.json
- src/types/index.ts
- src/utils/arvioinninAntajaListDecorator.ts
- src/views/arvioinnit-erikoistuva.vue
- src/views/arviointipyynto.vue
- Arviointipyyntöä lähetettäessä tai olemassaolevia arviointipyyntöjä suodatettaessa, haetaan listaan myös vastuuhenkilöt
- Erotellaan vastuuhenkilöt erillisellä maininnalla nimen yhteydessä
> UOELSA-558: Arviointipyynnön lähettäminen vastuuhenkilölle

- src/types/index.ts
- Poista opintojenAloitusvuosi joka poistettu backendissä ja lisää opintosuunnitelmaKaytossaPvm
> UOELSA-697: Muokkaa ErikoistuvaLaakari typeä

- src/components/asiakirjat/asiakirjat-content.vue
- src/locales/fi.json
- src/views/tyoskentelyjaksot/tyoskentelyjakso.vue
- Korjaa lisäksi teksti jos asiakirjoja ei ole: Ei hakutuloksia -> Ei asiakirjoja
> UOELSA-744: Estä työskentelyjakson poistaminen jos siihen kohdistuu tapahtumia

- src/api/index.ts
- src/router/index.ts
- Mikäli api-palauttaa 404 responsen, ohjaa käyttäjä 404-sivulle
> UOELSA-666: Ohjaa käyttäjä kirjautumissivulle mikäli api palauttaa 401  tai 403 responsen

- src/components/mobile-nav/mobile-nav.vue
- Lisää Osaaminen alavalikko
- Korjaa tyylit ja aseta scoped
> UOELSA-840: Korjaa mobiilimenu

- src/forms/seurantajakso-form.vue
- src/views/seurantakeskustelut/kouluttaja/seurantakeskustelut-kouluttaja.vue
- Seurantakeskustelun yhteisiä merkintöjä ei voi laittaa menneisyyteen
- Korjattu status teksti kun kouluttaja odottaa erikoistujalta yhteisiä merkintöjä
> Seurantakeskustelu korjauksia

- src/forms/seurantajakso-form.vue
- src/views/seurantakeskustelut/erikoistuva/seurantakeskustelut-erikoistuja.vue
- kouluttajan arvioinnin kenttien korjaus
- seuraava keskustelu 6kk päähän
> UOELSA-587: Kouluttajan arvioinnin kenttien korjaus

- src/app.vue
- src/components/tietosuojaseloste/tietosuojaseloste-content.vue
- src/components/tietosuojaseloste/tietosuojaseloste-modal.vue
- src/router/index.ts
- src/views/tietosuojaseloste/tietosuojaseloste.vue
Tietosuojaselosteeseen pitää pystyä linkkaamaan SAML metadatassa
> UOELSA-891: Tietosuojaseloste omalle sivulle

- src/mixins/navbar.ts
- src/utils/opintooikeus.ts
- src/views/kayton-aloitus/kayton-aloitus.vue
- api palauttaa jo ainoastaan voimassaolevat opinto-oikeudet, joiden tila sallii kirjautumisen
> UOELSA-1144: Poista opinto-oikeuksien suodatus voimassaolon ja tilan mukaan

- src/types/index.ts
- src/views/kayttajahallinta/uusi-erikoistuva-laakari.vue
- Korjaa opinto-oppaan tyypiksi OpintoopasSimple erikoistuvan kutsutoiminnossa
> UOELSA-1165: Korjaa opinto-oppaan tyypitys

- src/forms/terveyskeskuskoulutusjakso-form.vue
- src/locales/fi.json
- src/views/terveyskeskuskoulutusjakso/terveyskeskuskoulutusjakson-hyvaksynta.vue
- src/views/terveyskeskuskoulutusjakso/terveyskeskuskoulutusjakson-hyvaksyntapyynto.vue
- src/views/terveyskeskuskoulutusjakso/terveyskeskuskoulutusjakson-tarkistus.vue
- liitteiden lataus eri rooleille
- tekstikorjauksia
- form error
> UOELSA-834: Terveyskeskuskoulutusjakson korjauksia

- src/views/kayttajahallinta/kouluttaja.vue
Testattu lokaalisti.
https://gofore-support.atlassian.net/jira/software/c/projects/ELSASC/boards/216?modal=detail&selectedIssue=ELSASC-15
> ELSASC-15: Korjaa käyttäjän kouluttajanäkymän yliopistolistausbugi

- src/locales/fi.json
- src/views/valmistumispyynnot/vastuuhenkilo/valmistumispyynnot-vastuuhenkilo.vue
Vastuuhenkilön valmistumispyyntö näkymän välilehdet
> vastuuhenkilo-valmistumispyynnot-nakyma

- src/locales/fi.json
- src/views/etusivu/etusivu-vastuuhenkilo.vue
Vastuuhenkilön etusivun näkymä.
Lisätty YEK valmistumispyynnöt, 
seuranta välilehdet.
Puuttuu YEK seuranta välilehdeltä.
> vastuuhenkilo etusivu

- src/locales/fi.json
- src/views/valmistumispyynnot/virkailija/valmistumispyynnot-virkailija.vue
> yek-1156-virkailija-valmistumispyynto-korjaus

- azure-pipelines.yml
CI ajaa tarvittavat tarkistukset, PR trigger ajaa saman pipelinen turhaan uudestaan.
> PR triggerien poisto käytöstä

- .github/workflows/actions.yml
- Aja actions aina kun pr muuttuu
> GitHub actions korjauksia

- src/components/etusivu-cards/erikoistumisen-edistyminen-card.vue
Korjattu etusivun muut koulutukset yek valmistumiseen suorituspvm
> Elsa-768-muut-koulutukset-yek-pvm-korjaus

- src/components/koejakso-cards/vastuuhenkilon-arvio-card.vue
- src/locales/fi.json
Selkeytetty koejakson arvioinnin tekstejä erikoistujalle.
> ELSA-790: Koejakson arvioinnin tekstien selvennystä

- src/locales/fi.json
- src/router/index.ts
- src/views/kayton-aloitus/kayton-aloitus.vue
- src/views/valmistumispyynnot/vastuuhenkilo/valmistumispyynnon-hyvaksynta.vue
- YEK huomioiminen käytön aloituksessa
- Valmistumispyynnön hyväksynnän validaation korjaus
> ELSA-807: Bugikorjauksia

- src/forms/arviointi-form.vue
- src/locales/fi.json
Rajoitetaan suoritusarviointi lomakkeen 'jokin muu, tarkenna' lomakkeen pituus 255 merkkiin (sama kuin tietokannassa)
> ELSA-449: Rajoitetaan kentän pituutta

- src/views/kayttajahallinta/yhdista-kayttajatileja/erikoistujat-ja-kouluttajat.vue
Näytetään myös null authoriteetilla olevat erikoistujien listauksessa
> ELSA-864: Näytetään myös null authoriteetilla olevat
